version: '3.8'

services:
  spring:
    build:
      context: ./springboot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ai

  ai:
    build:
      context: ./ai_model
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
