version: '3.8'

# 로그 설정
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  spring:
    build:
      context: ./springboot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ai
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
    logging: *default-logging


  ai:
    build:
      context: ./ai_model
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768m
    logging: *default-logging
